name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            command: npm run cy:run
        - name: Allure report gen
          uses: cypress-io/github-action@v6
          with:
            command: npm run allure:open

        - name: Generate Allure Report
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: allure-results

        - name: Upload report
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: allure-cypress-cucumber-master-medic-clinic/allure-report
