name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Cypress run
          uses: cypress-io/github-action@v3
          with:
            working-directory: allure-cypress-cucumber-master-medic-clinic
            install-command: npm install
            build: npm run build
            start: npm start
        - name: Generate report
          run: cd allure-cypress-cucumber-master-medic-clinic && npm run allure:report
        - name: Upload report
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: allure-cypress-cucumber-master-medic-clinic/allure-report
