name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            command: npm run cy:run
        - name: Generate report
          run: cd allure-cypress-cucumber-master-medic-clinic && npm run allure:report
        - name: Upload report
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: allure-cypress-cucumber-master-medic-clinic/allure-report
